### ISSUE TITLE
Microsoft .dll phone error: Not Implemented

### ISSUE THREAD

**Issue by Aeons93** [jetspiking/WPAppInstall#1]
Hello, I am not sure what this error is actually. 

I have both Windows Phone 8.0 SDK and Windows Phone 8.1 SDK. I have unlocked the bootloader as well. Are there any other requirements I am missing?

![image](https://github.com/jetspiking/WPAppInstall/assets/37124781/241935e2-4022-4e22-ac9e-4358cccb6448)

**Comment by jetspiking** [comment]
@Aeons93 
In general the installation of the SDK's should prove sufficient. You could attempt to install the Lite SDK's as well, this might be the issue.

Can you navigate to the devices tab and share a screenshot? Is your device running Windows Phone 8 or Windows 10 mobile?

Which Microsoft Windows version are you using on your desktop that is running this application?

**Comment by Aeons93** [comment]
I am running Windows 10 Pro version 22H2. 
The phone is Windows 10 mobile on a Nokia Lumia 1520. 

I installed the Lite SDKs as well, but still the same error.
![image](https://github.com/jetspiking/WPAppInstall/assets/37124781/4a162b6b-e36c-45f4-a299-71b5c4487074)

**Comment by jetspiking** [comment]
@Aeons93 
You could verify the following:
--> Open Settings and navigate to Updates & Security > For Developers > Select sideload mode.
--> Make sure to select "Sideload" as deployment option, in your screenshot it is set to "None".
--> You could attempt to install a different .xap file as well.
--> If all else fails, deploy with the xap deploy included in the SDK's. I am wondering if this would also throw an error.

**Comment by Aeons93** [comment]
Setting to sideload mode actually worked. However, it seems the app I was trying to install, Opera Mini, was the thing causing the error I think. I tried using the SDK to install it and it worked with no errors, but the app would not start. WPAppInstall threw that same error still though. 
I tried installing another .xap file and it worked just fine with no error. 

Thank you for the help!
